# 编译器
CXX = clang++

# 编译选项
CXXFLAGS = -fcolor-diagnostics -fansi-escape-codes -g -std=c++17

# 目录
BIN_DIR = bin
SRC_DIR = src

# 源文件
SRC_SERVER = $(SRC_DIR)/server.cpp
SRC_CLIENT = $(SRC_DIR)/client.cpp

# 目标文件
TARGET_SERVER = $(BIN_DIR)/server
TARGET_CLIENT = $(BIN_DIR)/client

# 默认目标
all: $(TARGET_SERVER) $(TARGET_CLIENT)

# 编译server
$(TARGET_SERVER): $(SRC_SERVER)
	@mkdir -p $(BIN_DIR)
	$(CXX) $(CXXFLAGS) -o $(TARGET_SERVER) $(SRC_SERVER)

# 编译client
$(TARGET_CLIENT): $(SRC_CLIENT)
	@mkdir -p $(BIN_DIR)
	$(CXX) $(CXXFLAGS) -o $(TARGET_CLIENT) $(SRC_CLIENT)

# 清理目标
clean:
	rm -rf $(BIN_DIR)/*
